language: cpp

compiler:
- gcc
- clang
os:
 - linux

jobs:
  include:
  - name: "all projects"
    script:
    - cmake -H. -B_build
    - cmake --build _build
 

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ./script

    packages:
      - cmake
      - cmake-data

